[package]
name = "rust-atcoder"
version = "0.1.0"
authors = ["kou_cs <kou.cshu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "abc"
path = "src/abc/main.rs"